// <auto-generated />
namespace ShopNetwork.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Editdiscount : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Editdiscount));
        
        string IMigrationMetadata.Id
        {
            get { return "201811262310422_Edit discount"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
