// <auto-generated />
namespace ShopNetwork.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Changetypeofphone : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Changetypeofphone));
        
        string IMigrationMetadata.Id
        {
            get { return "201811141213454_Change type of phone"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
